### ISSUE TITLE
Feature Request: Search for talks

### ISSUE THREAD

**Issue by stevepiercy** [njl/progcom#10]
I would like to search for or filter talks by keyword or category so I can find those for which I know enough about or have sufficient interest in to give an opinion.

Currently I cannot see any method to search for or filter talks.

**Comment by njl** [comment]
That's on purpose!

**Comment by stevepiercy** [comment]
That purpose results in me reviewing no more talks.

I am not comfortable reviewing talks in which I have no knowledge of their subject matter or in which I have no interest.
