### ISSUE TITLE
How to create batch groups?

### ISSUE THREAD

**Issue by dcrosta** [njl/progcom#15]
Hey @njl -- as you saw on twitter, we're using progcom for PyGotham voting (still underway). So far we're in the screening stage, but I'm trying to look ahead to understand what batch groups are and how that voting period works -- basically, I want to play around with it on my local instance of progcom. I've set the `THIS_IS_BATCH` envvar, but I can't see how to assign talks to batches. Is that something that needs to be done manually in the DB or via a script or something?

**Comment by njl** [comment]
If I remember, from the rough_scores view in the admin, you can click in the batch group column to assign to batch groups.

**Comment by njl** [comment]
(There was also some clever stuff to try to auto-assign groups using gensim that I didn't really tweak enough to make usable.)

**Comment by dcrosta** [comment]
OK cool -- so I've manually created some for now, just to experiment. In the batch review screens, I see both a "Accept/Decline Talks" box, and a "Select Talks" box -- at a glance, they appear to serve a similar purpose, just with different UI. The data between them doesn't appear to be linked. 

How were these two features used for PyCon?

**Comment by dcrosta** [comment]
(Also if you'd rather chat by email than github, let me know)

**Comment by njl** [comment]
Might as well chat about it in public!

One of those is your vote for which talk in that topic should be advanced, one is selecting who is actually accepted vs rejected. Try looking at it again with a non-admin account, and it should be apparent.

For PyCon, we'd let a fair amount of votes accumulate in a group, until there was a clear winner or winners. Then I'd propose closing a group on the slack channel, with my suggestion for the accepted talks. If there weren't any objections, I'd mark the talks in that group as accepted and rejected and close the group. Sometimes I'd accept one talk, and ask the committee to coalesce around a second talk, leaving the group open.

**Comment by dcrosta** [comment]
Ah ha! It's because I'm an admin, OK, got it!

So how did you do batching -- did you put together all talks that were substantially similar, or just random pairings of 2 talks from among those with good ratings in screening? Any recommendations about how we ought to proceed?

**Comment by njl** [comment]
I did a first pass with really high-level groups, like "Python Language", "Machine Learning". I then broke those groups down into smaller and more specific groups, "Python Language (Internals)" and "Python Language (Advanced Features)". I tried to keep those groups at about 5-8 talks per, although some ballooned to 12. We then accepted two-ish talks from each group, and arrived at the slate of talks. This made sure we covered topics in a way that roughly reflected the talks that were submitted, and that we picked the best option when similar talks were submitted.

**Comment by dcrosta** [comment]
Cool. How many submissions (about) did PyCon '17 have, out of curiosity?

**Comment by njl** [comment]
576.

**Comment by dcrosta** [comment]
Wow.

OK, cool, thanks for your help and advice here!
