### ISSUE TITLE
Highlight or list talks with no discussion.

### ISSUE THREAD

**Issue by doobeh** [njl/progcom#6]
It'd be nice to list talks with no discussion-- at present the stats list those with high participation, but having a list of zero participation would help to solicit feedback either internally or to the author.

**Comment by njl** [comment]
Interesting. Most talks actually don't have discussion, and many don't really need much. It might be interesting to highlight controversial talks, where votes seem more out of alignment.

**Comment by njl** [comment]
As we're winding up the screening stage, most talks don't have a discussion. I suspect most talks don't need one; I think this is a good idea in theory, but practically, what we really need is for folks to look at talks without enough votes, which it already does.
